"use client";
import Link from "next/link";
import {useCallback,useEffect,useRef,useState} from "react";
import {collabApi,CollabApiError} from "./api";
type Model={id:string;name:string;model_id:string;project_name:string;version:number;enabled:boolean;credential_present:boolean;can_manage:boolean};
type Run={id:string;title:string;revision:string;workspace_status:string;recovery_status:string|null;result_code:string|null};
type Event={id:string;action:string;project_name:string|null;actor_name:string|null;resource_id:string;created_at:string;detail:unknown};
type Data={events:Event[];models:Model[];runs:Run[];mail:{transport:string;configured:boolean}};
export function Administration({organizationId}:{organizationId:string}){
 const [data,setData]=useState<Data|null>(null),[query,setQuery]=useState(""),[error,setError]=useState(""),[notice,setNotice]=useState(""),[busy,setBusy]=useState(false),[model,setModel]=useState<Model|null>(null),[run,setRun]=useState<Run|null>(null);
 const requestSequence=useRef(0),activeReads=useRef(0);
 const load=useCallback(async(q="",before?:string,statusOnly=false)=>{if(statusOnly&&activeReads.current)return;const sequence=++requestSequence.current;activeReads.current++;try{const next=await collabApi<Data>(`organizations/${organizationId}/administration?q=${encodeURIComponent(q)}${before?`&before=${before}`:""}`);if(sequence!==requestSequence.current)return;setData(old=>old&&statusOnly?{...next,events:old.events}:before&&old?{...next,events:[...old.events,...next.events]}:next);setError("");}catch(e){if(sequence===requestSequence.current){if(e instanceof CollabApiError&&[401,403,404].includes(e.status)){setData(null);setModel(null);setRun(null);}setError(e instanceof Error?e.message:"读取管理数据失败");}}finally{activeReads.current--;}},[organizationId]);
 useEffect(()=>{const sequence=requestSequence;void load();return()=>{sequence.current++;};},[load]);
 const hasPendingRecovery=!!data?.runs.some(r=>r.recovery_status==="pending");
 useEffect(()=>{if(!hasPendingRecovery||busy)return;const refresh=()=>{if(document.visibilityState==="visible")void load("",undefined,true);};const timer=setInterval(refresh,2500);document.addEventListener("visibilitychange",refresh);return()=>{clearInterval(timer);document.removeEventListener("visibilitychange",refresh);};},[hasPendingRecovery,busy,load]);
 async function submit(path:string,body:unknown){setBusy(true);setError("");try{await collabApi(path,body);setModel(null);setRun(null);setNotice("操作已记录，状态已刷新。");await load(query);}catch(e){setError(e instanceof Error?e.message:"操作失败");}finally{setBusy(false);}}
 return <section className="collab-settings-section" aria-label="运行与审计管理"><h2>运行与审计管理</h2><button type="button" className="collab-text-button" disabled={busy} onClick={()=>void load("",undefined,true)}>刷新运行与模型状态</button>{error&&<p role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}{data&&<>
 <h3>模型与凭据</h3><p>可在此启停模型或删除本机凭据。导入和轮换通过本机管理员命令完成，密钥不经过浏览器。停用将撤销现有模型能力，启用后需新建运行。</p>
 {data.models.map(m=><article className="collab-result-card" key={m.id}><strong>{m.project_name} · {m.name}</strong><p>{m.model_id} · {m.enabled?"已启用":"已停用"} · {m.credential_present?"本机凭据已配置":"本机凭据缺失"} · 版本 {m.version}</p>{m.can_manage?<button className="collab-button" disabled={busy} onClick={()=>setModel(m)}>管理模型</button>:<p>需要该项目维护者权限。</p>}</article>)}
 {!data.models.length&&<p>暂无项目模型。部署管理员可使用 npm run model:import 导入指定模型。</p>}
 {model&&<form className="collab-form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void submit(`models/${model.id}/manage`,{action:f.get("action"),reason:f.get("reason"),expectedVersion:model.version,idempotencyKey:crypto.randomUUID()});}}><h4>{model.name}</h4><label>模型操作<select name="action" aria-label="模型操作"><option value="disable">停用并撤销已有模型能力</option>{model.credential_present&&<option value="enable">启用以供新运行使用</option>}<option value="remove_credential">停用并删除本机凭据</option></select></label><label>模型操作说明<textarea name="reason" minLength={10} maxLength={2000} required/></label><label><input type="checkbox" required/>确认此操作可能中断使用该模型的 AI</label><button className="collab-button" disabled={busy}>提交模型操作</button><button type="button" className="collab-text-button" onClick={()=>setModel(null)}>取消</button></form>}
 <h3>异常运行</h3><p>这里只列出你有维护权限的待核查运行。核对进程退出证据后才能恢复；证据不足时可登记隔离处置并撤销模型和测试资源能力。旧工作区仍隔离，未知副作用和并发占用不被自动清除。</p>
 {data.runs.map(r=><article className="collab-result-card" key={r.id}><strong>{r.title}</strong><p>{r.workspace_status} · {r.recovery_status??"未发起核查"} {r.result_code??""}</p><button className="collab-button" disabled={busy} onClick={()=>setRun(r)}>处理异常运行</button></article>)}{!data.runs.length&&<p>没有待核查运行。</p>}
 {run&&<form className="collab-form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget),isolate=f.get("action")==="isolate";void submit(`runs/${run.id}/${isolate?"disposition":"actions"}`,{...(isolate?{}:{action:"recover"}),expectedRevision:run.revision,reason:f.get("reason"),idempotencyKey:crypto.randomUUID()});}}><h4>{run.title}</h4><label>处置方式<select aria-label="处置方式" name="action"><option value="recover">重新核对进程退出证据</option><option value="isolate">登记隔离并撤销外部资源能力</option></select></label><label>处置说明<textarea name="reason" minLength={10} maxLength={2000} required/></label><button className="collab-button" disabled={busy}>提交运行处置</button><button type="button" className="collab-text-button" onClick={()=>setRun(null)}>取消</button></form>}
 <h3>账户与邮件</h3><p>邮件模式：{data.mail.transport} · {data.mail.configured?"必要配置已存在，尚不代表投递验证成功":"缺少必要配置"}。SMTP 由部署管理员配置 PI_COLLAB_MAIL_TRANSPORT、SMTP_URL 和 SMTP_FROM。</p><p>全因子丢失由本机管理员核验身份后运行 npm run account:recover。一次性凭证 30 分钟有效；不会通过普通组织管理员账户绕过其他人的 MFA。<Link href="/account-recovery">打开账户恢复页面</Link></p>
 <h3>组织审计</h3><p>可检索操作名、操作者、项目和资源。非项目成员只能查看审计元信息，不能查看其操作详情。</p><form className="collab-form compact" onSubmit={e=>{e.preventDefault();void load(query);}}><label>检索审计<input maxLength={100} value={query} onChange={e=>setQuery(e.target.value)}/></label><button className="collab-button">检索</button></form>
 {data.events.map(e=><article className="collab-result-card" key={e.id}><strong>{e.action}</strong><p>{e.actor_name??"系统"} · {e.project_name??"团队"} · {new Date(e.created_at).toLocaleString()}</p>{e.detail!==null&&<details><summary>操作详情</summary><pre className="collab-prewrap">{JSON.stringify(e.detail,null,2)}</pre></details>}</article>)}{!data.events.length&&<p>没有匹配的审计记录。</p>}{data.events.length>0&&data.events.length%50===0&&<button className="collab-button" onClick={()=>void load(query,data.events.at(-1)?.id)}>读取更早记录</button>}
 </>}</section>;
}
