"use client";
import {useCallback,useEffect,useRef,useState,type FormEvent} from 'react';
import {collabApi,CollabApiError} from './api';
type Entry={id:string;repository_id:string;key:string;version:number;revision:number;parent_id:string|null;base_sha:string|null;kind:string;title:string;body:string;source_note:string;source_run_id:string|null;copied_from_id:string|null;task_id:string;body_hash:string;author_id:string;author_kind:string;author_name:string;status:string;review_note:string|null};
type Listing={role:string;entries:Entry[];repositories:{id:string;name:string;base_sha:string}[]};
const names:Record<string,string>={proposed:'待审核',approved:'已生效',rejected:'已拒绝',revoked:'已撤回',superseded:'已被新版本替代',decision:'设计决策',contract:'接口约定',lesson:'失败经验',verification:'验证方法'};
export function ProjectMemory({projectId,taskId,userId}:{projectId:string;taskId:string;userId:string}){
 const[data,setData]=useState<Listing|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[repository,setRepository]=useState(''),[key,setKey]=useState(''),[title,setTitle]=useState(''),[kind,setKind]=useState('decision'),[body,setBody]=useState(''),[source,setSource]=useState(''),[base,setBase]=useState(''),[allVersions,setAllVersions]=useState(false),[copied,setCopied]=useState<string|null>(null),[filter,setFilter]=useState('current'),[notes,setNotes]=useState<Record<string,string>>({}),[retry,setRetry]=useState(false);
 const pending=useRef<{endpoint:string;body:Record<string,unknown>}|null>(null);
 const refresh=useCallback(async()=>{const next=await collabApi<Listing>(`projects/${projectId}/memory`);setData(next);setRepository(old=>old||next.repositories[0]?.id||'');setBase(old=>old||next.repositories[0]?.base_sha||'');},[projectId]);
 useEffect(()=>{void refresh().catch(e=>setError(e.message));const timer=setInterval(()=>{if(document.visibilityState==='visible')void refresh().catch(e=>setError(e.message));},5000);return()=>clearInterval(timer);},[refresh]);
 async function send(endpoint:string,payload:Record<string,unknown>){setBusy(true);setError('');pending.current??={endpoint,body:payload};try{await collabApi(pending.current.endpoint,pending.current.body);pending.current=null;setRetry(false);await refresh();}catch(e){if(e instanceof CollabApiError&&e.status<500)pending.current=null;setRetry(!!pending.current);setError(e instanceof Error?e.message:'记忆操作未完成');}finally{setBusy(false);}}
 function propose(e:FormEvent){e.preventDefault();const parent=data?.entries.find(m=>m.repository_id===repository&&m.key===key&&m.status==='approved');void send(`tasks/${taskId}/memory`,{repositoryId:repository,key,title,kind,body,sourceNote:source,baseSha:allVersions?null:base,parentId:parent?.id??null,sourceRunId:null,copiedFromId:copied,idempotencyKey:crypto.randomUUID()});}
 function copy(m:Entry){setRepository(m.repository_id);setKey(m.key);setTitle(m.title);setKind(m.kind);setBody(m.body);setSource(`从记忆 ${m.key} v${m.version} 修订或恢复：${m.source_note}`.slice(0,2000));setBase(m.base_sha??data?.repositories.find(r=>r.id===m.repository_id)?.base_sha??'');setAllVersions(m.base_sha===null);setCopied(m.id);}
 const canPropose=data&&['maintainer','developer'].includes(data.role),locked=busy||retry;
 return <section className="collab-snapshots" aria-label="项目协作记忆"><h2>项目协作记忆</h2><p className="collab-muted collab-small">沉淀设计决策、接口约定、失败经验和验证方法。只有独立维护者批准的适用版本才进入 AI 协作上下文；记忆不授予权限，也不会自动执行其中的命令。</p>
 {error&&<p role="alert" className="collab-error">{error}</p>}{retry&&<button className="collab-button" disabled={busy} onClick={()=>pending.current&&void send(pending.current.endpoint,pending.current.body)}>重查同一记忆请求</button>}
 {canPropose&&<details><summary>提出或修订项目记忆</summary><form className="collab-form compact" onSubmit={propose}>
 <label>记忆仓库<select aria-label="记忆仓库" value={repository} onChange={e=>{setRepository(e.target.value);setBase(data?.repositories.find(r=>r.id===e.target.value)?.base_sha??'');setCopied(null);}}>{data.repositories.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></label>
 <label>记忆标识<input aria-label="记忆标识" required pattern="[a-z][a-z0-9_-]{0,63}" maxLength={64} value={key} onChange={e=>setKey(e.target.value)}/></label><label>记忆标题<input aria-label="记忆标题" required maxLength={160} value={title} onChange={e=>setTitle(e.target.value)}/></label>
 <label>记忆类型<select aria-label="记忆类型" value={kind} onChange={e=>setKind(e.target.value)}>{['decision','contract','lesson','verification'].map(k=><option key={k} value={k}>{names[k]}</option>)}</select></label>
 <label>记忆内容<textarea aria-label="记忆内容" required maxLength={6000} value={body} onChange={e=>setBody(e.target.value)}/></label><label>记忆来源与依据<textarea aria-label="记忆来源与依据" required minLength={10} maxLength={2000} value={source} onChange={e=>setSource(e.target.value)}/></label>
 <label className="collab-check"><input type="checkbox" checked={allVersions} onChange={e=>setAllVersions(e.target.checked)}/>适用于此仓库所有基线（须人工确认）</label>{!allVersions&&<label>适用基线 SHA<input aria-label="适用基线 SHA" required pattern="[a-f0-9]{40}" value={base} onChange={e=>setBase(e.target.value)}/></label>}
 {copied&&<p className="collab-muted collab-small">复制来源：{copied}。恢复旧内容会创建新提案，仍须独立审核。</p>}<button className="collab-button" disabled={locked||!repository}>提交记忆提案</button></form></details>}
 <label>记忆记录筛选<select aria-label="记忆记录筛选" value={filter} onChange={e=>setFilter(e.target.value)}><option value="current">生效与待审</option><option value="all">全部历史</option></select></label>
 {data?.entries.filter(m=>filter==='all'||['approved','proposed'].includes(m.status)).map(m=><article key={m.id} className="collab-snapshot-card" aria-label={`记忆 ${m.key} v${m.version}`}><h3>{m.title} · v{m.version}</h3><p>{names[m.status]} · {names[m.kind]} · {m.author_name}{m.author_kind==='agent'?' 的 AI 提议':''}</p><p className="collab-small collab-prewrap">适用基线：{m.base_sha??'此仓库所有基线'}<br/>内容校验：{m.body_hash}</p><pre className="collab-prewrap">{m.body}</pre><p className="collab-prewrap">来源：{m.source_note}</p><p className="collab-small">任务 {m.task_id.slice(0,8)}{m.source_run_id&&` · 运行 ${m.source_run_id.slice(0,8)}`}{m.copied_from_id&&` · 复制自 ${m.copied_from_id.slice(0,8)}`}</p>{m.review_note&&<p>审核 / 撤回说明：{m.review_note}</p>}
 {canPropose&&<button className="collab-text-button" disabled={locked} onClick={()=>copy(m)}>修订或恢复此内容</button>}
 {data.role==='maintainer'&&['proposed','approved'].includes(m.status)&&<div className="collab-form compact"><label>记忆处理说明<textarea aria-label={`记忆处理说明 ${m.key} v${m.version}`} minLength={10} maxLength={2000} value={notes[m.id]??''} onChange={e=>setNotes(old=>({...old,[m.id]:e.target.value}))}/></label><div className="collab-form-actions">{(m.status==='approved'?['revoke']:m.author_id===userId?['reject']:['approve','reject']).map(decision=><button key={decision} className="collab-button" disabled={locked||(notes[m.id]?.trim().length??0)<10} onClick={()=>void send(`memory/${m.id}`,{decision,expectedRevision:m.revision,bodyHash:m.body_hash,note:notes[m.id]})}>{decision==='approve'?'批准记忆':decision==='reject'?'拒绝记忆':'撤回记忆'}</button>)}</div></div>}
 </article>)}<p className="collab-muted collab-small">最多显示最近 200 项。撤回不会删除历史；AI 下次读取上下文时不再获得已撤回正文，但已经读到的内容不能从旧对话中抹去，必要时停止当前运行并重新开始。</p></section>;
}
