import assert from 'node:assert/strict';
export async function verifyMemory({base,projectId,owner,member,ownerContext,memberContext}){
 for(const page of [owner,member]){await page.goto(base);await page.locator('.collab-task-row').filter({hasText:'Member API task'}).click();}
 const a=owner.getByRole('region',{name:'项目协作记忆',exact:true}),b=member.getByRole('region',{name:'项目协作记忆',exact:true});await b.getByText('提出或修订项目记忆',{exact:true}).click();
 await b.getByLabel('记忆标识',{exact:true}).fill('shared-order-api');await b.getByLabel('记忆标题',{exact:true}).fill('订单接口设计约定');await b.getByLabel('记忆内容',{exact:true}).fill('订单状态采用 open/done，先验证兼容性再修改调用方。');await b.getByLabel('记忆来源与依据',{exact:true}).fill('来源于固定契约评审，由维护者复核适用基线后使用。');await b.getByRole('button',{name:'提交记忆提案',exact:true}).click();
 const proposed=a.getByRole('article',{name:'记忆 shared-order-api v1',exact:true});await proposed.waitFor();await proposed.getByLabel('记忆处理说明 shared-order-api v1',{exact:true}).fill('已独立核对来源与适用基线，批准此设计约定。');await proposed.getByRole('button',{name:'批准记忆',exact:true}).click();await proposed.getByText(/已生效 · 设计决策/).waitFor();
 await b.getByRole('article',{name:'记忆 shared-order-api v1',exact:true}).getByText(/已生效 · 设计决策/).waitFor();
 const view=await(await memberContext.request.get(`${base}/api/collab/projects/${projectId}/memory`)).json(),m=view.entries[0];assert.equal(m.status,'approved');assert.equal(m.base_sha,'a'.repeat(40));
 assert.equal((await fetch(`${base}/api/collab/projects/${projectId}/memory`)).status,401);
 const forbidden=await memberContext.request.post(`${base}/api/collab/memory/${m.id}`,{headers:{Origin:base},data:{expectedRevision:m.revision,bodyHash:m.body_hash,decision:'revoke',note:'Developer cannot revoke approved memory'}});assert.equal(forbidden.status(),403);
 await proposed.getByLabel('记忆处理说明 shared-order-api v1',{exact:true}).fill('接口约定已变化，撤回旧记忆等待重新审核。');await proposed.getByRole('button',{name:'撤回记忆',exact:true}).click();await proposed.waitFor({state:'detached'});await a.getByLabel('记忆记录筛选',{exact:true}).selectOption('all');await proposed.getByText(/已撤回 · 设计决策/).waitFor();
 await b.getByLabel('记忆记录筛选',{exact:true}).selectOption('all');await b.getByRole('article',{name:'记忆 shared-order-api v1',exact:true}).getByText(/已撤回 · 设计决策/).waitFor();await b.getByRole('article',{name:'记忆 shared-order-api v1',exact:true}).getByRole('button',{name:'修订或恢复此内容',exact:true}).click();await b.getByRole('button',{name:'提交记忆提案',exact:true}).click();const restored=a.getByRole('article',{name:'记忆 shared-order-api v2',exact:true});await restored.waitFor();await restored.getByText(/待审核 · 设计决策/).waitFor();
 const final=await(await ownerContext.request.get(`${base}/api/collab/projects/${projectId}/memory`)).json();assert.equal(final.entries[0].copied_from_id,m.id);assert.equal(final.entries[1].body_hash,m.body_hash);
 await restored.screenshot({path:'test-results/collab/memory-desktop.png'});await member.setViewportSize({width:390,height:844});await b.getByRole('article',{name:'记忆 shared-order-api v2',exact:true}).screenshot({path:'test-results/collab/memory-mobile.png'});assert.equal(await member.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
 console.log('PASS: two-member memory proposal, independent approval, version scope, revocation, immutable old content and reviewed restoration proposal, permission checks and responsive UI.');
}
