import {randomUUID,randomBytes,createHash} from 'node:crypto';
import path from 'node:path';
import {z} from 'zod';
import {asUser} from './database';
import {DomainError} from './policy';
import {previewPath,preparePreview,removePreview} from './preview-artifacts';
const root=()=>process.env.PI_COLLAB_DATA_DIR??path.resolve('.local');
const input=z.object({validationId:z.uuid(),title:z.string().trim().min(1).max(120),folder:previewPath,entry:previewPath.refine(v=>v.endsWith('.html'))}).strict();
export function previewOrigin(){const origin=process.env.PI_COLLAB_PREVIEW_ORIGIN;if(!origin)throw new DomainError('preview_not_configured','尚未配置独立预览来源。',503);const url=new URL(origin),web=new URL(process.env.BETTER_AUTH_URL!);if(url.origin===web.origin||url.pathname!=='/'||url.search||url.hash||url.username||url.password||!['http:','https:'].includes(url.protocol))throw new DomainError('preview_not_configured','预览必须使用独立来源。',503);return url.origin;}
export async function createPreview(user:string,task:string,raw:unknown){z.uuid().parse(task);const b=input.parse(raw);previewOrigin();const id=randomUUID();
 const src=await asUser(user,async db=>{const valid=await db.query('SELECT 1 FROM collab.validations WHERE id=$1 AND task_id=$2',[b.validationId,task]);if(!valid.rowCount)throw new DomainError('not_found','验证记录不存在。',404);return(await db.query('SELECT collab.begin_preview($1,$2,$3,$4,$5) AS result',[id,b.validationId,b.title,b.folder,b.entry])).rows[0].result;});
 try{const built=await preparePreview(root(),id,src.snapshotId,src.manifestHash,b.folder,b.entry);await asUser(user,db=>db.query('SELECT collab.finish_preview($1,$2,$3,$4)',[id,built.hash,built.files,built.bytes]));return{id,status:'ready'};}
 catch(e){await removePreview(root(),id);const code=e instanceof Error&&/^(preview_|invalid_preview)/.test(e.message)?e.message:'preview_artifact_invalid';await asUser(user,db=>db.query('SELECT collab.finish_preview($1,NULL,0,0,$2)',[id,code])).catch(()=>{});throw new DomainError(code,'无法从该检查点创建静态预览。请选择包含 HTML 和静态资源的目录，并核对排除文件。',409);}
}
export function listPreviews(user:string,task:string){z.uuid().parse(task);return asUser(user,async db=>{const t=(await db.query('SELECT project_id FROM collab.tasks WHERE id=$1',[task])).rows[0];if(!t)throw new DomainError('not_found','任务不存在。',404);const role=(await db.query('SELECT collab.project_role($1) AS role',[t.project_id])).rows[0].role;return{role,configured:!!process.env.PI_COLLAB_PREVIEW_ORIGIN,previews:(await db.query("SELECT *,CASE WHEN expires_at<=now() AND status='ready' THEN 'expired' ELSE status END AS status FROM collab.checkpoint_previews WHERE task_id=$1 ORDER BY created_at DESC LIMIT 30",[task])).rows,logs:(await db.query('SELECT r.* FROM collab.preview_requests r JOIN collab.checkpoint_previews p ON p.id=r.preview_id WHERE p.task_id=$1 ORDER BY r.id DESC LIMIT 50',[task])).rows};});}
export async function openPreview(user:string,id:string){z.uuid().parse(id);const origin=previewOrigin(),token=randomBytes(32).toString('hex'),digest=createHash('sha256').update(token).digest('hex');const result=await asUser(user,async db=>(await db.query('SELECT collab.open_preview($1,$2) AS result',[id,digest])).rows[0].result);return{url:`${origin}/preview/${token}/${result.entry.split('/').map(encodeURIComponent).join('/')}`,expiresAt:result.expiresAt};}
export function revokePreview(user:string,id:string,raw:unknown){z.uuid().parse(id);const b=z.object({reason:z.string().trim().min(10).max(2000)}).strict().parse(raw);return asUser(user,async db=>{await db.query('SELECT collab.revoke_preview($1,$2)',[id,b.reason]);return{ok:true};});}
