import { DomainError } from "./policy";
import { z } from "zod";
import { asUser } from "./database";
import { projectRole, uuid } from "./projects";
export const environmentInput=z.object({action:z.enum(["reset","reclaim"]),expectedVersion:z.number().int().positive(),reason:z.string().trim().min(10).max(2000),acknowledgeLoss:z.literal(true),idempotencyKey:z.uuid()}).strict();
export function projectEnvironments(user:string,project:string){uuid.parse(project);return asUser(user,async db=>{const role=await projectRole(db,project,"project.read");return {canManage:role==="maintainer",environments:(await db.query(`SELECT e.*,r.status AS resource_status,t.title,w.status AS workspace_status FROM collab.workspace_environments e JOIN collab.resources r ON r.id=e.resource_id JOIN collab.workspaces w ON w.id=e.workspace_id JOIN collab.runs run ON run.workspace_id=w.id JOIN collab.tasks t ON t.id=run.task_id WHERE e.project_id=$1 ORDER BY e.created_at DESC LIMIT 100`,[project])).rows};});}
export function manageEnvironment(user:string,workspace:string,raw:unknown){uuid.parse(workspace);const input=environmentInput.parse(raw);return asUser(user,async db=>(await db.query("SELECT collab.manage_environment($1,$2) AS result",[workspace,input])).rows[0].result);}

export const environmentRecipeInput=z.object({install:z.enum(["none","npm-ci"]),expectedVersion:z.number().int().nonnegative(),reason:z.string().trim().min(10).max(2000)}).strict();
export function environmentRecipe(user:string,project:string){uuid.parse(project);return asUser(user,async db=>{const role=await projectRole(db,project,"project.read");return {canManage:role==="maintainer",recipe:(await db.query("SELECT id,version,install,reason,created_at FROM collab.environment_recipes WHERE project_id=$1 ORDER BY version DESC LIMIT 1",[project])).rows[0]??{version:0,install:"none"}};});}
export function publishEnvironmentRecipe(user:string,project:string,raw:unknown){uuid.parse(project);const b=environmentRecipeInput.parse(raw);return asUser(user,async db=>(await db.query("SELECT collab.publish_environment_recipe($1,$2,$3,$4) AS result",[project,b.install,b.expectedVersion,b.reason])).rows[0].result);}
export function environmentHandoff(user:string,run:string){uuid.parse(run);return asUser(user,async db=>{const r=(await db.query("SELECT r.id,r.status,t.title,t.description,t.acceptance,m.name AS model_name FROM collab.runs r JOIN collab.tasks t ON t.id=r.task_id LEFT JOIN collab.model_profiles m ON m.id=r.model_profile_id WHERE r.id=$1",[run])).rows[0];if(!r)throw new DomainError("not_found","运行不存在或不可访问。",404);return {run:r,environment:(await db.query("SELECT recipe,status,evidence FROM collab.run_environments WHERE run_id=$1",[run])).rows[0]??null};});}
