import { guardWebAdmission } from "./operations";
import { auth } from "./auth";
import { DomainError } from "./policy";
import { ZodError } from "zod";

export async function identity(request: Request) {
  const session = await auth().api.getSession({ headers: request.headers });
  if (!session) throw new DomainError("unauthenticated", "Sign in to continue", 401);
  return session;
}

export function requireSameOrigin(request: Request) {
  if (["GET", "HEAD", "OPTIONS"].includes(request.method)) return;
  const origin = request.headers.get("origin");
  const expected = new URL(process.env.BETTER_AUTH_URL ?? "http://127.0.0.1:30142").origin;
  if (origin !== expected) throw new DomainError("untrusted_origin", "A same-origin request is required", 403);
}

export async function jsonBody(request: Request, limit = 64 * 1024): Promise<unknown> {
  if (!request.headers.get("content-type")?.startsWith("application/json")) throw new DomainError("invalid_content_type", "JSON is required", 415);
  const text = await request.text();
  if (Buffer.byteLength(text) > limit) throw new DomainError("body_too_large", `Request exceeds ${limit / 1024} KiB`, 413);
  try { return JSON.parse(text); }
  catch { throw new DomainError("invalid_json", "Invalid JSON request"); }
}

export async function endpoint(request: Request, operation: () => Promise<unknown>, successStatus = 200): Promise<Response> {
  try {
    requireSameOrigin(request);
    await guardWebAdmission(request);
    const result = await operation();
    return result instanceof Response ? result : Response.json(result, { status: successStatus, headers: { "Cache-Control": "no-store" } });
  } catch (error) {
    if (error instanceof DomainError) return Response.json({ error: error.code, message: error.message }, { status: error.status });
    if (error instanceof ZodError) return Response.json({ error: "validation", message: error.issues[0]?.message ?? "Invalid input" }, { status: 400 });
    const pgCode = (error as { code?: string })?.code;
    const domainMessages: Record<string, [number, string]> = {
      revert_acknowledgement_required: [400, "请确认撤回范围和全部冲突选择，并填写至少 10 个字符的说明。"],
      revert_validation_required: [409, "请使用支持撤回冲突检查的新版执行器重新验证快照。"],
      invalid_revert: [400, "请填写撤回任务名称和至少 10 个字符的原因。"],
      revert_source_unavailable: [409, "撤回来源或当前基线已变化，请刷新并重新创建撤回任务。"],
      revert_executor_upgrade_required: [409, "此撤回任务需要新版执行器，请联系实例管理员升级。"],
      organization_deleted: [409, "团队已删除，请由执行删除的所有者先恢复。"],
      stale_organization: [409, "团队状态已变化，请刷新后重新确认。"],
      invalid_organization_action: [400, "请完整输入团队名称、操作原因并核对操作。"],
      organization_busy: [409, "团队仍有活动作业或未核实的结果，请刷新团队信息并处理阻塞项。"],
      transfer_mfa_required: [409, "接任所有者必须先启用多因素验证。"],
      invalid_discussion_context: [400, "请选择本任务讨论中的 1–20 条评论，并填写交接说明。"],
      discussion_context_too_large: [413, "所选讨论过长，请减少评论或缩短交接说明后重新预览。"],
      discussion_context_changed: [409, "所选讨论的来源信息已变化，请重新预览后确认。"],
      invalid_notification_preferences: [400, "静默结束时间应在未来 30 天内。"],
      stale_notification_preferences: [409, "通知设置已在另一窗口变化，请刷新后重试。"],
      invalid_subtask: [400, "请核对子任务目标、验收、确认与操作说明。"],
      stale_subtask: [409, "子任务提案或成果已变化，请刷新后重新操作。"],
      subtask_source_unavailable: [409, "父运行目标、依赖、基线或授权已变化；请使用当前有效的普通 AI 运行提出新子任务。"],
      subtask_principal_required: [403, "启动子代理需要父运行的发起人确认，并持有当前控制权；不能代他人启动计费运行。"],
      subtask_limit: [409, "子任务数量、深度或待确认提案达到上限，请处理现有提案或调整项目配额。"],
      evidence_limit: [413, "关联证据超出一次导出上限，请使用单项证据入口；不会生成截断的完整证据包。"],
      invalid_service_preview: [400, "请核对动态预览启动命令、时长与临时数据确认。"],
      service_preview_limit: [409, "项目最多 4 个活动或待核查的动态预览，请先停止现有服务。"],
      service_preview_busy: [429, "动态预览请求较多，请稍后重试。"],
      invalid_history_archive: [400, "请选择有效的 Pi JSONL 会话文件。"],
      history_archive_quota: [409, "完整归档超过额度：每位成员每项目最多 50 组或 100 MiB，项目共 1 GiB。请先删除不再需要的自有归档。"],
      artifact_budget_exhausted: [409, "产物存储额度不足或计量未知，请查看资源页面。"],
      artifact_protected: [409, "产物仍被引用、未到保留期限或退出尚未确认，不能清理。"],
      artifact_expired: [409, "来源工作区已回收，请选择仍保留的快照或重新运行。"],
      artifact_cleanup_pending: [409, "已有清理正在处理，请查看原记录。"],
      invalid_artifact_operation: [400, "请核对产物额度、保留期限和操作说明。"],
      invalid_oidc: [400, "请检查组织登录配置和变更原因。"],
      oidc_unavailable: [403, "组织身份提供方已变化、停用或成员权限已撤销，请重新登录。"],
      oidc_local_account_required: [409, "解除绑定前需要保留可用的本地密码登录。"],
      invalid_gitlab_operation: [400, "请核对 GitLab 操作和说明。"],
      gitlab_connection_unavailable: [409, "GitLab 连接不可用，请联系管理员。"],
      gitlab_already_imported: [409, "此仓库已导入。"],
      gitlab_import_required: [409, "请先导入 GitLab 仓库。"],
      gitlab_source_unavailable: [409, "成果或投递来源已变化，请重新选择。"],
      gitlab_confirmation_required: [409, "请打开固定变更预览并确认发送。"],
      gitlab_operation_exists: [409, "同一目标已有操作，请查看原记录；结果未知时不能重复发送。"],
      invalid_gitlab_review: [400, "请打开固定变更预览并填写至少 10 个字符的评审说明。"],
      invalid_terminal_run: [400, "共享终端当前支持原生运行，无需选择模型。"],
      invalid_terminal_input: [400, "终端输入或尺寸不符合要求。"],
      editor_frozen: [409, "草稿已冻结、移交或文件已删除；未同步的本地内容请导出保存。"],
      editor_handoff_required: [409, "任务正在人工共编。要边编辑边用 AI，请打开共享文件，在右侧选择“当前文件 AI”。若要将整个任务交接给 AI，再冻结版本并选择交给 AI，或归档草稿。"],
      editor_source_mismatch: [409, "共编版本与恢复来源不一致，且不能同时应用代码建议。"],
      editor_version_used: [409, "该版本已交给另一次运行，请打开原运行。"],
      editor_exists: [409, "任务已有共编草稿，请打开现有草稿。"],
      editor_document_limit: [409, "草稿最多 40 个文件，每人每个文件最多 8 个在线窗口。"],
      editor_client_conflict: [409, "编辑窗口标识冲突，请保存本地内容后重新打开。"],
      invalid_editor_command: [400, "请填写版本说明并检查操作。"],
      installation_draining: [503, "实例正在排空升级，暂不接收新作业。"],
      account_recovery_unavailable: [409, "恢复凭证无效、已使用或已到期。"],
      invalid_admin_query: [400, "检索文字过长。"],
      invalid_model_action: [400, "请核对模型操作及修改说明。"],
      model_credential_missing: [409, "模型凭据已删除，请本机管理员重新导入或轮换密钥。"],
      invalid_environment: [400, "请填写操作原因并确认测试数据删除。"],
      environment_capacity_exhausted: [429, "工作区测试环境名额已满，请回收已停止的环境。"],
      invalid_capacity: [400, "请核对并发、费用设置和修改说明。"],
      invalid_scheduling: [400, "请核对项目优先级、设置版本和修改说明。"],
      invalid_question: [400, "请填写有效的问题或回答。"],
      question_closed: [409, "问题已回答或运行已停止，请刷新查看当前状态。"],
      invalid_pull_release: [400, "请填写评审或交付说明，核对版本并明确确认。"],
      stale_pull_release: [409, "PR 代码、权限、评审或 CI 已变化，请重新读取当前版本。"],
      independent_review_required: [403, "任务负责人和 PR 发起人不能为自己的变更提供独立评审。"],
      pull_release_not_ready: [409, "需要独立批准、当前 CI 通过以及与操作匹配的草稿状态。"],
      pull_release_busy: [409, "此 PR 已有交付操作或未知结果，请先核对原记录。"],
      invalid_discussion: [400, "请核对讨论内容、成员和版本。"],
      invalid_mention: [400, "提及的成员已不在此项目中。"],
      discussion_resolved: [409, "讨论已解决，请重新打开后继续。"],
      suggestion_source_unavailable: [409, "代码建议与所选快照不匹配，请刷新后核对固定版本。"],
      invalid_control_request: [400, "请填写控制权版本及至少 10 个字符的申请或处理说明。"],
      invalid_run_instruction: [400, "请检查指令内容、类型与控制权版本。"],
      stale_control: [409, "控制权或申请已变化，请刷新后确认当前控制者。"],
      already_controller: [409, "你已经是当前运行的控制者。"],
      control_closed: [409, "本次运行已停止接收指令或尚未进入可指挥阶段。"],
      control_request_pending: [409, "你已有待处理的接管申请，请等待或撤回原申请。"],
      control_request_revoked: [409, "申请人的权限已改变，需要重新申请控制权。"],
      control_delivery_pending: [409, "有指令正在投递或结果未知，暂不能交接。请等待或先停止运行。"],
      control_queue_full: [429, "待处理申请或指令已达到上限，请等待现有操作完成。"],
      invalid_task_edit: [400, "请填写任务标题、状态和至少 10 个字符的修改原因。"],
      task_status_managed: [409, "进行中与待合并状态由执行和交付流程管理，不能手动设置。"],
      task_completion_acknowledgement: [400, "请确认你已核对任务验收标准；标记完成不会批准或合并代码。"],
      resolution_task_fixed: [409, "修复任务的目标与验收已绑定原整合，不能在此更改。"],
      task_edit_unchanged: [409, "任务内容和状态未改变。"],
      setup_unavailable: [409, "初始化已完成或令牌无效。"], account_exists: [409, "账户已存在，请登录。"],
      invitation_unavailable: [409, "邀请已失效、被撤销或已使用。"], invitation_email_mismatch: [403, "请使用受邀邮箱对应的账户。"],
      inviter_no_longer_authorized: [403, "邀请者权限已变更，请联系团队管理员重新邀请。"],
      sign_in_required: [401, "该邮箱已有账户，请先登录后重新打开邀请。"], registration_required: [400, "请填写姓名和新账户密码。"],
      membership_disabled: [403, "此团队成员已停用，请联系管理员。"], last_owner: [409, "团队必须至少保留一位启用的所有者。"],
      mfa_required: [403, "请先在账户安全中启用多因素验证。"], forbidden: [403, "没有执行此操作的权限。"], invalid_role: [400, "无效的角色。"],
      not_found: [404, "资源不存在或不可访问。"], idempotency_conflict: [409, "此请求编号已用于不同的操作，请重新提交。"],
      stale_revision: [409, "任务已更新，请刷新后重新提交。"], task_closed: [409, "任务已关闭。"],
      task_busy: [409, "该任务已有活动运行，或旧执行者尚待对账。"],
      invalid_run_action: [400, "请填写至少 10 个字符的处理原因，并刷新运行版本。"],
      recovery_pending: [409, "已有对账请求等待处理，请稍后刷新。"],
      run_not_reconciling: [409, "此运行已经不处于待对账状态，请刷新。"],
      workspace_not_stopped: [409, "必须先确认运行和旧写入进程停止，并核对工作区状态。"],
      invalid_workspace_git: [400, "请核对 Git 版本、选择、提交说明及明确确认。"],
      workspace_git_busy: [409, "已有 Git 操作、推送预览或快照占用此工作区，请等待原操作或申请核查。"],
      invalid_task_push_preview: [400, "请核对源提交、检查版本或至少 10 个字符的取消原因。"],
      task_push_preview_limit: [429, "推送预览已达到当前项目或分支数量限制。"],
      invalid_task_push_confirmation: [400, "请确认全部提交、完整目标与披露范围，撤回需填写至少 10 个字符的原因。"],
      stale_task_push_confirmation: [409, "成员、任务或仓库关联已变化，请重新生成预览并确认。"],
      task_push_destination_busy: [409, "此远端任务分支已有推送或 PR 创建占用，请先处理原操作；未知结果不能释放占用。"],
      invalid_task_push_delivery: [400, "请明确确认发送原固定导出；取消需 10 个字符原因，封存需 20 个字符原因及未知结果确认。"],
      task_push_delivery_exists: [409, "此导出已有发送任务，请查看原任务，不能再次发送。"],
      task_push_delivery_owned: [409, "此确认已归发送任务所有，请查看或取消原任务。结果未知时目标持续占用。"],
      task_push_not_unknown: [409, "只有结果未知的发送任务可以封存。"],
      invalid_task_pull_proposal: [400, "请核对 PR 标题、说明、任务版本或至少 10 个字符的取消原因。"],
      task_pull_source_unavailable: [409, "需要已确认接收的推送，以及仍有效的 GitHub 仓库关联。"],
      task_pull_proposal_busy: [409, "此推送已有 PR 提案正在准备，请查看原提案。"],
      task_pull_proposal_limit: [429, "此项目已有 20 项待处理的 PR 提案。"],
      invalid_task_pull_delivery: [400, "请确认完整 PR 内容、版本和通知影响；取消需 10 个字符原因，封存需 20 个字符原因及未知结果确认。"],
      task_pull_delivery_exists: [409, "此提案已有创建任务，请查看原记录，不能再次发送。"],
      stale_task_pull_proposal: [409, "提案、权限、任务或仓库关联已改变，请重新准备提案。"],
      task_pull_delivery_limit: [429, "此项目已有 20 项正在处理的 PR 创建任务。"],
      task_pull_not_unknown: [409, "只有结果未知的 PR 创建任务可以封存。"],
      invalid_pull_checks: [400, "请核对任务和 CI 规则版本。"],
      invalid_pull_checks_policy: [400, "请填写明确的检查名称、GitHub App ID、有效期和规则变更原因。"],
      pull_checks_source_unavailable: [409, "需要当前固定代码版本与已发布的 CI 规则。"],
      pull_checks_busy: [409, "此版本已有 CI 读取任务，请查看原记录。"],
      pull_checks_limit: [429, "此项目已有 20 项 CI 读取任务。"],
      invalid_pull_revision: [400, "请核对固定代码版本；取消需要至少 10 个字符的原因。"],
      pull_revision_busy: [409, "此 PR 已有代码读取任务，请查看原记录。"],
      pull_revision_limit: [429, "此项目已有 20 项 PR 代码读取任务。"],
      pull_revision_source_unavailable: [409, "请先读取当前 PR 状态，并核验仓库关联。"],
      pull_revision_unavailable: [409, "固定代码版本尚未就绪或校验失败。"],
      invalid_pull_observation: [400, "请核对 PR 观察版本；取消需要至少 10 个字符的原因。"],
      pull_observation_busy: [409, "此 PR 已有读取任务，请查看原记录。"],
      pull_observation_limit: [429, "此项目已有 20 项 PR 读取任务。"],
      pull_observation_source_unavailable: [409, "PR 的仓库关联或安装已失效，请重新核验关联后读取。"],
      task_push_confirmation_limit: [429, "此项目已有 20 项未撤回的推送确认。"],
      workspace_git_limit: [429, "该项目已有 20 项未完成的工作区 Git 操作。"],
      invalid_snapshot: [400, "请填写交接说明并确认运行版本。"],
      invalid_validation: [400, "验证配置或执行证据格式无效。"],
      invalid_task_result: [400, "请填写成果说明并确认任务版本。"],
      invalid_work_intent: [400, "请检查修改范围、变更类型和预计完成时间。"],
      invalid_resource: [400, "请检查测试资源名称与参数。"], resource_limit: [400, "已达到测试资源或作业额度。"],
      invalid_github_sync: [400, "请确认当前基线、允许安全快进并填写至少 10 个字符的原因。"],
      stale_github_sync: [409, "仓库基线已变化，请刷新并重新确认。"],
      github_connection_unavailable: [409, "GitHub 安装关联已停用或需要重新核验。"],
      github_sync_target_busy: [409, "目标正在同步、整合、推进或等待核查。"],
      github_sync_busy: [409, "原同步仍在执行，请等待或先请求取消。"],
      github_sync_limit: [400, "该项目已有 20 项未完成的仓库同步。"],
      invalid_github_import: [400, "请核对安装、GitHub 仓库编号、项目内名称和至少 10 个字符的原因。"],
      github_repository_unavailable: [409, "该仓库当前不可导入，请由团队管理员核对关联或未完成的导入。"],
      github_import_busy: [409, "原导入仍在执行，请等待或先请求取消。"],
      github_import_limit: [400, "该项目已有 20 项未完成的仓库导入。"],
      invalid_github_connection: [400, "请填写至少 10 个字符的原因，并核对 GitHub 关联版本。"],
      stale_github_connection: [409, "GitHub 关联已变化，请刷新后重试。"],
      invalid_promotion: [400, "请确认评审版本、排除范围并填写至少 10 个字符的推进说明。"],
      promotion_not_ready: [409, "推进条件已变化：请重新检查目标、来源、必跑规则、独立批准与修改要求。"],
      promotion_target_busy: [409, "目标正在整合、推进或等待对账，请等待原操作得到确认。"],
      promotion_not_reconciling: [409, "该推进当前不需要对账，请刷新状态。"],
      invalid_integration: [400, "请检查整合成果、验证配置或取消原因。"],
      invalid_resolution: [400, "请填写修复任务名称、负责人和至少 10 个字符的修复目标。"],
      resolution_exists: [409, "此冲突已有修复任务，请刷新后打开原任务。"],
      resolution_source_unavailable: [409, "需要仍有效且有必跑规则的冲突记录；来源、规则、目标或权限变化后须重新整合。"],
      resolution_dependencies_fixed: [409, "修复任务的原始依赖已固定，不能追加或替换。请从新的整合记录创建修复任务。"],
      resolution_validation_required: [409, "修复必须使用固定的必跑配置，且保留来源链、移除冲突标记并重新验证。"],
      resolution_acknowledgement_required: [409, "请明确确认所有冲突选择，并填写至少 10 个字符的修复说明。"],
      resolution_overlap: [409, "所选成果包含修复成果与其已覆盖的输入，或两份修复覆盖了相同输入。请仅选择所需的完整修复成果。"],
      invalid_integration_policy: [400, "请检查必跑验证、批准人数和规则变更原因。"],
      stale_integration_policy: [409, "整合规则已变化，请刷新规则后重新提交。"],
      required_integration_profile: [409, "必须使用当前整合规则指定的验证配置。"],
      invalid_integration_review: [400, "请检查评审版本、决定和评审说明。"],
      integration_not_reviewable: [409, "需要当前规则下检查通过的整合；代码、规则或权限已变化时请重新整合。"],
      integration_self_approval: [403, "整合申请人、来源运行发起人和成果发布人不能批准此组合。"],
      stale_integration_review: [409, "你的评审已在另一窗口更新，请刷新后重新提交。"],
      integration_stale: [409, "目标基线已经变化，请刷新后重新创建整合。"],
      integration_source_unavailable: [409, "成果或依赖已过期、被撤回或不属于同一仓库，请更新成果后重试。"],
      integration_limit: [400, "整合最多包含 32 项成果，每项目最多 20 项活动整合。"],
      invalid_resource_action: [400, "请填写 10 至 2000 个字符的资源处理原因，并检查操作参数。"],
      stale_resource: [409, "资源已被其他操作修改，请刷新后重试。"],
      resource_state_changed: [409, "资源状态已经变化，请刷新后重新选择操作。"],
      resource_not_drained: [409, "旧资源租约或数据库作业尚未退出，暂时不能恢复。"],
      preview_source_unavailable: [409, "需要已通过验证的固定快照。"],
      preview_unavailable: [409, "预览已失效、已撤回或尚未完成。"],
      preview_limit: [409, "每项目最多 20 个活动预览；静态目录最多 200 文件和 8 MiB。"],
      invalid_preview: [400, "请核对预览名称、静态目录、HTML 入口和操作说明。"],
      invalid_memory: [400, "请检查记忆内容、来源、适用版本及审核说明。"],
      invalid_memory_source: [400, "记忆来源必须属于当前任务与仓库。"],
      stale_memory: [409, "记忆已被更新或撤回，请刷新后按当前版本操作。"],
      memory_limit: [409, "每仓库最多 32 条生效记忆，每项目最多 100 条待审提案。"],
      invalid_note: [400, "请检查说明内容与引用版本。"],
      coordination_rate_limit: [429, "协作说明提交过于频繁，请稍后重试。"],
      invalid_contract: [400, "请检查契约内容、JSON mock、确认版本与裁决原因。"],
      stale_contract: [409, "契约已经发布或基准版本已变化，请基于当前版本重新提案。"],
      contract_scope_changed: [409, "受影响任务范围已变化，请重新提案并取得当前任务的确认。"],
      contract_confirmation_required: [409, "仍有任务尚未有效确认，或明确拒绝。请取得负责人确认，或由维护者填写裁决原因。"],
      contract_owner_mismatch: [409, "该契约标识已由另一任务负责，请从原任务修订。"],
      contract_limit: [400, "单个提案最多影响 128 个任务，每次运行最多锁定 32 项契约。"],
      contract_runtime_unsupported: [409, "契约输入当前只支持本机运行。"],
      intent_run_closed: [409, "运行已停止或权限已变化，不能补写范围声明。请在新运行中重新声明。"],
      result_validation_unavailable: [409, "需要当前依赖与契约版本下通过验证的快照。旧运行、缺少软依赖或过期输入必须重新运行与验证。"],
      invalid_withdrawal: [400, "请填写至少 10 个字符的撤回原因。"],
      invalid_dependency: [400, "无效的依赖类型。"], dependency_cycle: [409, "该依赖会形成循环。"], dependency_limit: [400, "每个任务最多 32 个直接依赖。"],
      dependency_runtime_unsupported: [409, "当前只有本机运行支持固定版本依赖输入。"],
      validation_source_unavailable: [409, "快照尚未就绪，或验证配置与仓库、运行后端不匹配。"],
      validation_busy: [409, "此快照已有验证运行，或旧验证的结果仍待核查。"],
      snapshot_pending: [409, "已有快照请求等待处理，请稍后刷新。"],
      snapshot_unavailable: [409, "快照不可用，或与当前任务、仓库及运行后端不匹配。"],
      model_unavailable: [409, "模型配置不可用，请选择已启用的项目模型。"],
      last_maintainer: [409, "项目必须保留一位有效维护者，请先授予其他成员维护者权限。"],
      stale_membership: [409, "成员权限已被其他操作修改，请刷新后再保存。"],
      project_member_ineligible: [400, "目标必须是当前团队中已启用的成员；新成员需先接受团队邀请。"],
      project_member_exists: [409, "成员已有项目记录，请在成员列表中调整权限。"],
      project_membership_disabled: [403, "项目成员资格已停用，请联系项目维护者重新授权。"],
      recovery_reason_required: [400, "请填写至少 10 个字符的应急接管原因。"],
      already_maintainer: [409, "你已是项目维护者，无需应急接管。"],
      invalid_owner: [400, "负责人必须是项目中已启用的开发者或维护者。"],
      repository_revision_unavailable: [409, "仓库或基线版本不可用，请刷新仓库信息。"], invalid_run: [400, "无效的运行参数。"],
    };
    const domainCode = error instanceof Error ? error.message : "";
    if (pgCode === "P0001" && domainMessages[domainCode]) {
      const [status, message] = domainMessages[domainCode];
      return Response.json({ error: domainCode, message }, { status });
    }
    if (pgCode === "42501") return Response.json({ error: "forbidden", message: "Operation is not permitted" }, { status: 403 });
    if (pgCode === "23503" || pgCode === "23505") return Response.json({ error: "conflict", message: "The resource conflicts with the current project state" }, { status: 409 });
    console.error("[pi-collab] request failed", error instanceof Error ? error.message : "Unknown error");
    return Response.json({ error: "internal", message: "The request could not be completed" }, { status: 500 });
  }
}
