import type { z } from "zod";
import { asUser } from "./database";
import { projectRole,uuid } from "./projects";
import { DomainError } from "./policy";
import { integrationInput,integrationCancelInput } from "./integration-schema";
export function requestIntegration(userId:string,projectId:string,raw:z.infer<typeof integrationInput>){
 uuid.parse(projectId);const input=integrationInput.parse(raw);
 return asUser(userId,async db=>{await projectRole(db,projectId,"project.read");if(!(await db.query("SELECT 1 FROM collab.repositories WHERE id=$1 AND project_id=$2",[input.repositoryId,projectId])).rowCount)throw new DomainError("not_found","仓库不存在或不可访问。",404);return(await db.query("SELECT collab.request_integration($1,$2,$3,$4,$5,$6) AS result",[input.repositoryId,input.targetSha,input.resultIds,input.profileId,input.idempotencyKey,input.expectedPolicyId??null])).rows[0].result;});
}
export function listIntegrations(userId:string,projectId:string){
 uuid.parse(projectId);return asUser(userId,async db=>{await projectRole(db,projectId,"project.read");
  const integrations=(await db.query("SELECT id,runtime,repository_id,target_branch,target_sha,profile_id,policy_id,root_result_ids,sources,input_hash,status,stop_requested,error_code,created_at,finished_at,collab.integration_state(id) AS input_state,collab.integration_review_state(id) AS review_state,(requested_by=collab.actor() OR collab.project_role(project_id)='maintainer') AS can_cancel,evidence->>'candidateCommit' AS candidate_commit,evidence->'conflict' AS conflict,COALESCE(evidence->'snapshot'->'excluded','[]'::jsonb) AS excluded,(SELECT jsonb_object_agg(s.task_id,t.title) FROM collab.integration_sources s JOIN collab.tasks t ON t.id=s.task_id WHERE s.integration_id=collab.integrations.id) AS source_titles,(SELECT jsonb_build_object('id',t.id,'title',t.title) FROM collab.resolution_tasks rt JOIN collab.tasks t ON t.id=rt.task_id WHERE rt.integration_id=collab.integrations.id) AS resolution_task FROM collab.integrations WHERE project_id=$1 ORDER BY created_at DESC,id LIMIT 50",[projectId])).rows;
  const results=(await db.query("SELECT r.id,r.task_id,t.title,r.version,w.repository_id,r.worktree_commit,collab.run_dependency_state(r.source_run_id) AS input_state FROM collab.task_results r JOIN collab.tasks t ON t.current_result_id=r.id JOIN collab.snapshots s ON s.id=r.snapshot_id JOIN collab.workspaces w ON w.id=s.workspace_id WHERE r.project_id=$1 AND NOT EXISTS(SELECT 1 FROM collab.result_withdrawals WHERE result_id=r.id) ORDER BY t.title,t.id LIMIT 100",[projectId])).rows;
  const promotions=(await db.query("SELECT p.* FROM unnest($1::uuid[]) candidate(id) CROSS JOIN LATERAL (SELECT id,integration_id,status,promotion_sha,stop_requested,error_code FROM collab.promotions WHERE integration_id=candidate.id ORDER BY requested_at DESC,id LIMIT 10) p",[integrations.map(i=>i.id)])).rows;
  return {integrations:integrations.map(i=>({...i,promotions:promotions.filter(p=>p.integration_id===i.id)})),results};});
}
export function integrationDetail(userId:string,id:string){uuid.parse(id);return asUser(userId,async db=>{const row=(await db.query("SELECT id,runtime,status,target_branch,target_sha,input_hash,sources,profile_id,policy_id,evidence,error_code,collab.integration_review_state(id) AS review_state,collab.integration_state(id) AS input_state FROM collab.integrations WHERE id=$1",[id])).rows[0];if(!row)throw new DomainError("not_found","整合记录不存在或不可访问。",404);
 const policy=row.policy_id?(await db.query("SELECT p.id,p.version,p.repository_id,p.target_branch,p.profile_id,p.required_approvals,p.reviewer_approvals,p.reason,p.created_by,p.created_at,v.config FROM collab.integration_policies p JOIN collab.validation_profiles v ON v.id=p.profile_id WHERE p.id=$1",[row.policy_id])).rows[0]:null;
 const reviewHistory=(await db.query("SELECT id,reviewer_id,version,decision,note,revision_hash,organization_version::text,project_version::text,created_at FROM collab.integration_reviews WHERE integration_id=$1 ORDER BY created_at DESC,id DESC LIMIT 100",[id])).rows;
 return {integration:row,policy,reviewHistory,reviewHistoryLimit:100};});}
export function cancelIntegration(userId:string,id:string,raw:z.infer<typeof integrationCancelInput>){uuid.parse(id);const input=integrationCancelInput.parse(raw);return asUser(userId,async db=>(await db.query("SELECT collab.cancel_integration($1,$2,$3) AS result",[id,input.reason,input.idempotencyKey])).rows[0].result);}
