import test,{before,after} from "node:test";
import assert from "node:assert/strict";
import {randomBytes,randomUUID} from "node:crypto";
import {Pool} from "pg";
import {localConfig,connectionString,applicationEnvironment} from "../../scripts/local-config";
import {startNativeDatabase} from "../../scripts/native-database";
import {migrate} from "../../scripts/migrate";
import {provisioningAuth} from "../../lib/collab/auth";
import {database,asUser} from "../../lib/collab/database";
import {createTask} from "../../lib/collab/tasks";
import {startRun} from "../../lib/collab/runs";
import {createProject} from "../../lib/collab/projects";
import {administration,manageModel,recordDisposition} from "../../lib/collab/administration";
import {registerModelProfile} from "../../lib/collab/gateway/profiles";
import {rotateModelCredential} from "../../lib/collab/gateway/rotate";
import {openCredential} from "../../lib/collab/gateway/credentials";
import {redeemAccountRecovery} from "../../lib/collab/account-recovery";
import {tokenHash} from "../../lib/collab/onboarding";
const config=await localConfig(),name=`pi_collab_test_${randomBytes(6).toString("hex")}`,native=await startNativeDatabase(config);
Object.assign(process.env,applicationEnvironment(config),{DATABASE_URL:connectionString(config,false,name)});
const admin=new Pool({connectionString:connectionString(config,true,name)}),organization=randomUUID(),users:string[]=[],password=randomBytes(20).toString("hex"),key=randomBytes(32);
let project:string,profile:string;const auth=provisioningAuth(admin);
before(async()=>{await migrate(config,name);for(let i=0;i<3;i++)users.push((await auth.api.signUpEmail({body:{email:`admin${i}@test.invalid`,name:`Admin fixture ${i}`,password}})).user.id);
 await admin.query("INSERT INTO collab.organizations(id,name,created_by) VALUES($1,'Administration fixture',$2)",[organization,users[0]]);
 for(let i=0;i<2;i++)await admin.query("INSERT INTO collab.memberships(organization_id,user_id,role) VALUES($1,$2,$3)",[organization,users[i],i?"admin":"owner"]);
 await admin.query('UPDATE public."user" SET "twoFactorEnabled"=true WHERE id=ANY($1)',[users.slice(0,2)]);
 project=(await createProject(users[0],{organizationId:organization,name:"Managed project",description:""})).id;
 profile=(await registerModelProfile(admin,key,{projectId:project,actorId:users[0],name:"Admin model",modelId:"fixture-model"},{apiKey:"fixture-before-rotation",baseUrl:"http://127.0.0.1:9/v1"})).id;
});
after(async()=>{await Promise.all([admin.end(),database().end()]);globalThis.__piCollabPool=undefined;const cleanup=new Pool({connectionString:connectionString(config,true,"postgres")});await cleanup.query(`DROP DATABASE "${name}" WITH (FORCE)`);await cleanup.end();await native.stop();key.fill(0);});
test("administration foundation: organization audit search respects tenant and project detail boundaries",async()=>{
 await asUser(users[0],async db=>{await db.query("INSERT INTO collab.audit_events(organization_id,project_id,actor_id,action,resource_id,detail) VALUES($1,$2::uuid,$3,'fixture.private_detail',$2::uuid::text,$4)",[organization,project,users[0],{note:"private project detail"}]);});
 const own=await administration(users[0],organization,"fixture.private",null),otherAdmin=await administration(users[1],organization,"fixture.private",null);
 assert.equal(own.events.length,1);assert.equal(own.events[0].detail.note,"private project detail");assert.equal(otherAdmin.events[0].detail,null);assert.equal(otherAdmin.events[0].project_name,"Managed project");
 assert.equal((await administration(users[0],organization,"fixture.private",own.events[0].id)).events.length,0);
 await assert.rejects(administration(users[2],organization,"",null),/not_found/);
 assert.equal(JSON.stringify(own).includes("fixture-before-rotation"),false);
});
test("administration foundation: model disable, immutable versions, credential removal and explicit rotation",async()=>{
 const body={action:"disable",reason:"Disable model for administrator acceptance",expectedVersion:1,idempotencyKey:randomUUID()};
 await assert.rejects(manageModel(users[1],profile,body),/not_found|forbidden/);const disabled=await manageModel(users[0],profile,body);assert.equal(disabled.enabled,false);assert.deepEqual(await manageModel(users[0],profile,body),disabled);
 await assert.rejects(manageModel(users[0],profile,{...body,idempotencyKey:randomUUID()}),/stale_revision/);
 const removed=await manageModel(users[0],profile,{...body,action:"remove_credential",expectedVersion:disabled.version,idempotencyKey:randomUUID()});
 await assert.rejects(manageModel(users[0],profile,{...body,action:"enable",expectedVersion:removed.version,idempotencyKey:randomUUID()}),/model_credential_missing/);
 const rotated=await rotateModelCredential(admin,key,{profileId:profile,actorId:users[0],expectedVersion:removed.version,reason:"Restore explicitly selected fixture credential"},{apiKey:"fixture-after-rotation",baseUrl:"http://127.0.0.1:9/v1"});assert.equal(rotated.enabled,false);
 const sealed=(await admin.query("SELECT sealed FROM collab_gateway.credentials WHERE profile_id=$1",[profile])).rows[0].sealed;assert.equal(openCredential(key,profile,project,sealed).apiKey,"fixture-after-rotation");
 assert.equal((await manageModel(users[0],profile,{...body,action:"enable",expectedVersion:rotated.version,idempotencyKey:randomUUID()})).enabled,true);
});
test("administration foundation: disposition revokes capabilities while preserving quarantine and unknown outcomes",async()=>{
 const repository=randomUUID(),executor=randomUUID();await admin.query("INSERT INTO collab.repositories(id,organization_id,project_id,name,provider,base_sha,default_branch) VALUES($1,$2,$3,'Fixture','local',$4,'main')",[repository,organization,project,"a".repeat(40)]);
 const task=await createTask(users[0],project,{title:"Unknown process fixture",description:"",acceptance:""});const run=await startRun(users[0],task.id,{repositoryId:repository,baseSha:"a".repeat(40),expectedVersion:task.version,prompt:"No model inference",modelProfileId:profile,idempotencyKey:randomUUID()});
 const claim=(await admin.query("SELECT collab_worker.claim_resolution_aware($1,'native') AS result",[executor])).rows[0].result;
 await admin.query("SELECT collab_worker.issue_model_capability($1,$2,$3,$4)",[executor,run.runId,claim.run.epoch,"f".repeat(64)]);await admin.query("SELECT collab_worker.mark_running($1,$2,$3)",[executor,run.runId,claim.run.epoch]);
 await admin.query("UPDATE collab.workspaces SET lease_expires_at=clock_timestamp()-interval '1 minute' WHERE id=$1",[claim.workspace.id]);await admin.query("SELECT collab_worker.reconcile_expired()");
 const current=(await administration(users[0],organization,"",null)).runs.find((r:{id:string})=>r.id===run.runId);assert.ok(current);
 const body={expectedRevision:current.revision,reason:"Keep old workspace quarantined pending host inspection",idempotencyKey:randomUUID()};
 await assert.rejects(recordDisposition(users[1],run.runId,body),/forbidden|not_found/);const response=await recordDisposition(users[0],run.runId,body);assert.deepEqual(await recordDisposition(users[0],run.runId,body),response);
 const state=(await admin.query("SELECT r.status,w.status AS workspace_status FROM collab.runs r JOIN collab.workspaces w ON w.id=r.workspace_id WHERE r.id=$1",[run.runId])).rows[0];assert.equal(state.status,"reconciling");assert.equal(state.workspace_status,"quarantined");
 assert.equal((await admin.query("SELECT revoked FROM collab_gateway.capabilities WHERE run_id=$1",[run.runId])).rows[0].revoked,true);
});
test("account recovery foundation: host-only single-use ticket resets all factors and invalidates prior sessions and authorizations",async()=>{
 const token=randomBytes(32).toString("hex"),newPassword=randomBytes(20).toString("hex");
 await assert.rejects(database().query("SELECT collab_admin.issue_account_recovery($1,$2,$3)",["admin0@test.invalid",tokenHash(token),"Verified recovery fixture identity in person"]),/permission/);
 await assert.rejects(admin.query('UPDATE public."user" SET "twoFactorEnabled"=false WHERE id=$1',[users[0]]),/mfa_required/);
 await admin.query('INSERT INTO public."twoFactor"(id,"userId",secret,"backupCodes",verified) VALUES($1,$2,$3,$4,true)',[randomUUID(),users[0],"fixture-secret","fixture-backup"]);
 await admin.query('INSERT INTO public.verification(id,identifier,value,"expiresAt","createdAt","updatedAt") VALUES($1,$2,$3,now()+interval \'1 hour\',now(),now())',[randomUUID(),"reset-password:oldfixture",users[0]]);
 await (await auth.$context).internalAdapter.createSession(users[0]);
 const version=(await admin.query("SELECT authorization_version::text FROM collab.memberships WHERE organization_id=$1 AND user_id=$2",[organization,users[0]])).rows[0].authorization_version;
 await admin.query("SELECT collab_admin.issue_account_recovery($1,$2,$3)",["admin0@test.invalid",tokenHash(token),"Verified recovery fixture identity in person"]);
 assert.equal((await redeemAccountRecovery({token,password:newPassword})).recovered,true);
 assert.equal((await admin.query('SELECT 1 FROM public.session WHERE "userId"=$1',[users[0]])).rowCount,0);
 assert.equal((await admin.query('SELECT "twoFactorEnabled" AS mfa FROM public."user" WHERE id=$1',[users[0]])).rows[0].mfa,false);
 assert.equal((await admin.query('SELECT 1 FROM public."twoFactor" WHERE "userId"=$1',[users[0]])).rowCount,0);assert.equal((await admin.query('SELECT 1 FROM public.verification WHERE value=$1',[users[0]])).rowCount,0);
 assert.ok(BigInt((await admin.query("SELECT authorization_version FROM collab.memberships WHERE organization_id=$1 AND user_id=$2",[organization,users[0]])).rows[0].authorization_version)>BigInt(version));
 await assert.rejects(redeemAccountRecovery({token,password:newPassword}),/凭证无效/);await assert.rejects(auth.api.signInEmail({body:{email:"admin0@test.invalid",password}}));
 const login=await auth.api.signInEmail({body:{email:"admin0@test.invalid",password:newPassword}});assert.ok("user" in login&&login.user.id===users[0]);
 await assert.rejects(administration(users[0],organization,"",null),/mfa_required/);
 assert.equal((await admin.query("SELECT 1 FROM collab_admin.recovery_authority")).rowCount,0);
});
