import test,{before,after} from "node:test";
import assert from "node:assert/strict";
import {randomBytes,randomUUID} from "node:crypto";
import {Pool} from "pg";
import {localConfig,connectionString,applicationEnvironment} from "../../scripts/local-config";
import {startNativeDatabase} from "../../scripts/native-database";
import {migrate} from "../../scripts/migrate";
import {provisioningAuth} from "../../lib/collab/auth";
import {database,asUser} from "../../lib/collab/database";
import {createProject} from "../../lib/collab/projects";
import {importHistory,listHistory,readHistory,deleteHistory} from "../../lib/collab/history";
import {previewPiHistory} from "../../lib/collab/history-format";
import {createTask} from "../../lib/collab/tasks";
import {startRun} from "../../lib/collab/runs";
import {operationInventory} from "../../scripts/operations-core";
const config=await localConfig(),name=`pi_collab_test_${randomBytes(6).toString("hex")}`,native=await startNativeDatabase(config);
Object.assign(process.env,applicationEnvironment(config),{DATABASE_URL:connectionString(config,false,name)});
const admin=new Pool({connectionString:connectionString(config,true,name)}),organization=randomUUID(),users:string[]=[],password=randomBytes(20).toString("hex");let project:string;
before(async()=>{await migrate(config,name);const auth=provisioningAuth(admin);for(let i=0;i<3;i++)users.push((await auth.api.signUpEmail({body:{email:`history${i}@test.invalid`,name:`History fixture ${i}`,password}})).user.id);
 await admin.query("INSERT INTO collab.organizations(id,name,created_by) VALUES($1,'History fixture',$2)",[organization,users[0]]);
 for(let i=0;i<2;i++)await admin.query("INSERT INTO collab.memberships(organization_id,user_id,role) VALUES($1,$2,$3)",[organization,users[i],i?"member":"owner"]);
 await admin.query('UPDATE public."user" SET "twoFactorEnabled"=true WHERE id=ANY($1)',[users.slice(0,2)]);
 project=(await createProject(users[0],{organizationId:organization,name:"History project",description:""})).id;
 await admin.query("INSERT INTO collab.project_memberships(organization_id,project_id,user_id,role) VALUES($1,$2,$3,'developer')",[organization,project,users[1]]);
});
after(async()=>{await Promise.all([admin.end(),database().end()]);globalThis.__piCollabPool=undefined;const cleanup=new Pool({connectionString:connectionString(config,true,"postgres")});await cleanup.query(`DROP DATABASE "${name}" WITH (FORCE)`);await cleanup.end();await native.stop();});
test("history preview excludes host paths, system, thinking, tool results and images",()=>{
 const raw=[{type:"session",id:"private-id",cwd:"/private/path"},{type:"message",message:{role:"system",content:"secret system"}},{type:"message",message:{role:"user",content:"selected question"}},{type:"message",message:{role:"assistant",content:[{type:"thinking",thinking:"private thought"},{type:"text",text:"selected answer"},{type:"toolCall",arguments:{apiKey:"secret"}}]}},{type:"message",message:{role:"toolResult",content:"private tool output"}}].map(x=>JSON.stringify(x)).join("\n");
 assert.deepEqual(previewPiHistory(raw),[{role:"user",text:"selected question"},{role:"assistant",text:"selected answer"}]);assert.throws(()=>previewPiHistory("not json"));
});
test("selected history is private by default, explicitly shared, idempotent and owner-removable",async()=>{
 const input={title:"Selected discussion",messages:[{role:"user",text:"Reviewed question"}],shared:false,reviewed:true};
 const result=await importHistory(users[0],project,input);assert.equal((await importHistory(users[0],project,input)).id,result.id);
 assert.equal((await listHistory(users[1],project)).histories.length,0);await assert.rejects(readHistory(users[1],project,result.id),/不可访问/);
 const shared=await importHistory(users[0],project,{...input,shared:true});assert.equal((await listHistory(users[1],project)).histories.length,1);
 assert.equal((await readHistory(users[1],project,shared.id)).messages[0].text,"Reviewed question");
 await assert.rejects(readHistory(users[2],project,shared.id),/不可访问/);await assert.rejects(deleteHistory(users[1],project,shared.id),/不可删除/);
 await asUser(users[1],async db=>assert.equal((await db.query("SELECT 1 FROM collab.imported_histories WHERE id=$1",[result.id])).rowCount,0));
 assert.throws(()=>importHistory(users[0],project,{...input,reviewed:false}));await deleteHistory(users[0],project,shared.id);assert.equal((await listHistory(users[1],project)).histories.length,0);
});
test("drain rejects new database admissions and preserves existing run cancellation",async()=>{
 const repo=randomUUID();await admin.query("INSERT INTO collab.repositories(id,organization_id,project_id,name,provider,base_sha,default_branch) VALUES($1,$2,$3,'Drain fixture','local',$4,'main')",[repo,organization,project,"a".repeat(40)]);
 const task=await createTask(users[0],project,{title:"Drain fixture task",description:"",acceptance:""});
 const request={repositoryId:repo,baseSha:"a".repeat(40),expectedVersion:task.version,prompt:"No model inference",idempotencyKey:randomUUID()};
 await admin.query("UPDATE collab_meta.operations SET draining=true");
 await assert.rejects(startRun(users[0],task.id,request),/installation_draining/);
 const state=await operationInventory(admin);assert.equal(state.draining,true);assert.equal(state.ready,true);
 await assert.rejects(database().query("UPDATE collab_meta.operations SET draining=false"),/permission/);
 await admin.query("UPDATE collab_meta.operations SET draining=false");const run=await startRun(users[0],task.id,request);assert.ok(run.runId);
 await admin.query("UPDATE collab_meta.operations SET draining=true");assert.equal((await operationInventory(admin)).ready,false);
 await asUser(users[0],db=>db.query("SELECT collab.stop_run($1,$2)",[run.runId,randomUUID()]));assert.equal((await operationInventory(admin)).ready,true);
});
