import test, { before, after } from "node:test";
import assert from "node:assert/strict";
import { randomBytes, randomUUID } from "node:crypto";
import { mkdtemp, mkdir, readFile, writeFile, rm } from "node:fs/promises";
import { execFile } from "node:child_process";
import { promisify } from "node:util";
import { tmpdir } from "node:os";
import path from "node:path";
import { Pool } from "pg";
import { localConfig, applicationEnvironment, connectionString, executorConnectionString } from "../../scripts/local-config";
import { startNativeDatabase } from "../../scripts/native-database";
import { migrate } from "../../scripts/migrate";
import { provisioningAuth } from "../../lib/collab/auth";
import { database, asUser } from "../../lib/collab/database";
import { createProject } from "../../lib/collab/projects";
import { createTask } from "../../lib/collab/tasks";
import { startRun, runDetail } from "../../lib/collab/runs";
import { ExecutionStore } from "../../lib/collab/execution-store";
import { snapshotCode } from "../../lib/collab/discussions";
import { type CodeAnchor, type SnapshotFile } from "../../lib/collab/discussion-schema";
import { requestSnapshot } from "../../lib/collab/snapshots";
import { captureSnapshot, snapshotSummary } from "../../lib/collab/runtime/snapshots";
import { createWorkspace } from "../../lib/collab/runtime/workspace";
import { executeClaim } from "../../lib/collab/executor";
import { NativeRuntimeBackend } from "../../lib/collab/runtime/backends";

const config = await localConfig(), name = `pi_collab_test_${randomBytes(6).toString("hex")}`, native = await startNativeDatabase(config);
const root = await mkdtemp(path.join(tmpdir(),"pi-collab-discussions-"));
Object.assign(process.env, applicationEnvironment(config), { DATABASE_URL: connectionString(config, false, name), PI_COLLAB_DATA_DIR:root });
const admin = new Pool({ connectionString: connectionString(config, true, name) });
const store = new ExecutionStore(executorConnectionString(config, name));
const org = randomUUID(), repository = randomUUID(), executor = randomUUID(), users: string[] = [], exec=promisify(execFile);
const repo=path.join(root,"repositories",repository,"git");
let project: string, base: string;
before(async () => {
 await migrate(config, name); const auth = provisioningAuth(admin);
 for(let i=0;i<5;i++)users.push((await auth.api.signUpEmail({body:{name:`Discussion ${i}`,email:`discussion${i}@test.invalid`,password:randomBytes(20).toString("hex")}})).user.id);
 await admin.query("INSERT INTO collab.organizations(id,name,created_by) VALUES($1,'Discussion team',$2)",[org,users[0]]);
 for(let i=0;i<4;i++)await admin.query("INSERT INTO collab.memberships(organization_id,user_id,role) VALUES($1,$2,$3)",[org,users[i],i===0?"owner":"member"]);
 await admin.query('UPDATE public."user" SET "twoFactorEnabled"=true WHERE id=$1',[users[0]]);
 project=(await createProject(users[0],{organizationId:org,name:"Discussion flow",description:""})).id;
 for(let i=1;i<4;i++)await admin.query("INSERT INTO collab.project_memberships(organization_id,project_id,user_id,role) VALUES($1,$2,$3,$4)",[org,project,users[i],i===1?"developer":i===2?"reviewer":"viewer"]);
 await mkdir(repo,{recursive:true});for(const args of [["init"],["config","user.name","Discussion test"],["config","user.email","discussions@test.invalid"]])await exec("git",args,{cwd:repo});
 await writeFile(path.join(repo,"code.txt"),"one\ntwo\nthree\n");await exec("git",["add","."],{cwd:repo});await exec("git",["commit","-m","Initial"],{cwd:repo});base=(await exec("git",["rev-parse","HEAD"],{cwd:repo})).stdout.trim();
 await admin.query("INSERT INTO collab.repositories(id,organization_id,project_id,name,provider,base_sha,default_branch) VALUES($1,$2,$3,'Local code','local',$4,'main')",[repository,org,project,base]);
});
after(async()=>{await store.close();await database().end();globalThis.__piCollabPool=undefined;await admin.end();const cleanup=new Pool({connectionString:connectionString(config,true,"postgres")});await cleanup.query(`DROP DATABASE "${name}" WITH (FORCE)`);await cleanup.end();await native.stop();await rm(root,{recursive:true,force:true});});
const task=()=>createTask(users[1],project,{title:"Human terminal work",description:"",acceptance:""});
async function codeFixture(){
 const t=await task(),run=await startRun(users[1],t.id,{repositoryId:repository,baseSha:base,prompt:"Prepare version",expectedVersion:t.version,idempotencyKey:randomUUID()});
 const claim=(await store.claim(executor,"native"))!;assert.equal(claim.run.id,run.runId);
 const workspace=await createWorkspace(root,claim.workspace.id,repo,base);
 await store.running(executor,run.runId,claim.run.epoch);await store.finish(executor,run.runId,claim.run.epoch,"completed",{});
 const detail=await runDetail(users[1],run.runId);
 const requested=await requestSnapshot(users[1],run.runId,{expectedRevision:detail.run.revision,note:"Code review snapshot",idempotencyKey:randomUUID()});
 const pending=(await store.pendingSnapshots()).find(s=>s.id===requested.snapshotId)!;
 const { id, runId, workspaceId, repositoryId, baseSha, note, context, parentSnapshot, dependencies, contracts, resolution } = pending;
 const source = { id, runId, workspaceId, repositoryId, baseSha, note, context, parentSnapshot, dependencies, contracts, resolution };
 const saved=await captureSnapshot(root,source);await store.completeSnapshot(pending.id,saved.manifestHash,snapshotSummary(saved.manifest),null);
 const file=await snapshotCode(users[2],pending.id,{path:"code.txt"}) as SnapshotFile;
 const anchor:CodeAnchor={snapshotId:pending.id,manifestHash:file.manifestHash,path:file.path,fileHash:file.fileHash,startLine:2,endLine:2};
 return {t,workspace,anchor};
}
import { requestRunControl,decideRunControl,runControl,submitRunInstruction } from "../../lib/collab/run-control";
import { inspectNativeExit } from "../../lib/collab/runtime/receipts";
import { sessionProcesses } from "../../lib/collab/runtime/process-session";
import { openEditor } from "../../lib/collab/editor";
const poll=async(check:()=>Promise<boolean>)=>{const deadline=Date.now()+12000;while(Date.now()<deadline){if(await check())return;await new Promise(r=>setTimeout(r,50));}assert.fail("Terminal condition timeout");};
const input=(user:string,run:string,version:string,command:unknown,key=randomUUID())=>asUser(user,async db=>(await db.query("SELECT collab.submit_terminal_input($1,$2,$3,$4) AS result",[run,version,key,command])).rows[0].result);
test("real shared PTY persists input once, transfers controller, keeps shell state and stops all ordinary session jobs",async()=>{
 const t=await task(),request={repositoryId:repository,baseSha:base,prompt:"Human terminal session",expectedVersion:t.version,idempotencyKey:randomUUID(),executionKind:"terminal" as const};
 const accepted=await startRun(users[1],t.id,request);assert.equal((await startRun(users[1],t.id,request)).runId,accepted.runId);await assert.rejects(startRun(users[1],t.id,{...request,executionKind:"ai"}),/idempotency_conflict/);
 const claim=(await store.claim(executor,"native"))!;assert.equal(claim.run.execution_kind,"terminal");let ready!:()=>void;const started=new Promise<void>(r=>{ready=r;});
 const work=executeClaim(store,executor,claim,{dataRoot:root,backend:new NativeRuntimeBackend(),driver:async agent=>{ready();return{kind:"terminal",...(await agent.peer.command("terminal_wait",{},20000)).data as object};}});
 await Promise.race([started,work.then(async outcome=>{throw new Error(`Terminal failed before ready: ${outcome} ${JSON.stringify((await admin.query("SELECT summary FROM collab.runs WHERE id=$1",[accepted.runId])).rows[0])}`);})]);
 const command={type:"input",data:"mkdir sub; cd sub; printf 'ALPHA\\n' >> result.txt; printf 'PTY_READY\\n'\r"},key=randomUUID(),submitted=await input(users[1],accepted.runId,"1",command,key);assert.equal((await input(users[1],accepted.runId,"1",command,key)).instructionId,submitted.instructionId);
 const checkout=path.join(root,"workspaces",claim.workspace.id,"checkout");await poll(async()=>{try{return await readFile(path.join(checkout,"sub/result.txt"),"utf8")==="ALPHA\n";}catch{return false;}});
 await assert.rejects(input(users[0],accepted.runId,"1",{type:"input",data:"bad\r"}),/forbidden/);
 await assert.rejects(submitRunInstruction(users[1],accepted.runId,{expectedVersion:"1",idempotencyKey:randomUUID(),kind:"steer",message:"AI must not run inside human terminal"}),/not_found/);
 await poll(async()=>(await runControl(users[1],accepted.runId)).instructions[0].status==="delivered");
 const q=await requestRunControl(users[0],accepted.runId,{expectedVersion:"1",idempotencyKey:randomUUID(),note:"接手终端继续操作并保留当前目录"});await decideRunControl(users[1],q.requestId,{expectedVersion:"1",idempotencyKey:randomUUID(),action:"accept",note:"交接已确认，继续使用同一个终端"});
 await assert.rejects(input(users[1],accepted.runId,"1",{type:"input",data:"echo OLD\r"}),/forbidden/);
 await input(users[0],accepted.runId,"2",{type:"resize",cols:101,rows:31});await input(users[0],accepted.runId,"2",{type:"input",data:"stty size > dimensions.txt; printf 'BETA\\n' >> result.txt; sleep 60 &\r"});
 await poll(async()=>{try{return await readFile(path.join(checkout,"sub/result.txt"),"utf8")==="ALPHA\nBETA\n";}catch{return false;}});assert.equal((await readFile(path.join(checkout,"sub/dimensions.txt"),"utf8")).trim(),"31 101");
 const receipt=JSON.parse(await readFile(path.join(root,"runtime-receipts",`${claim.workspace.id}.json`),"utf8"));assert.ok((await sessionProcesses(receipt.terminalSession)).length>=2);
 await input(users[0],accepted.runId,"2",{type:"input",data:"exit\r"});assert.equal(await work,"completed");assert.equal((await sessionProcesses(receipt.terminalSession)).length,0);
 assert.equal((await inspectNativeExit(root,claim.workspace.id,{runId:accepted.runId,executorId:executor,epoch:claim.run.epoch})).safe,true);
 const events=await admin.query("SELECT payload FROM collab.run_events WHERE run_id=$1 AND kind='run.output'",[accepted.runId]);assert.match(JSON.stringify(events.rows),/PTY_READY/);
});
test("manual terminal respects shared draft gate and snapshot restoration without issuing model capability",async()=>{
 const f=await codeFixture(),t=(await admin.query("SELECT version FROM collab.tasks WHERE id=$1",[f.t.id])).rows[0];
 const session=await openEditor(users[1],f.t.id,{snapshotId:f.anchor.snapshotId,expectedVersion:t.version});
 const request={repositoryId:repository,baseSha:base,prompt:"Human handoff",expectedVersion:t.version,idempotencyKey:randomUUID(),snapshotId:f.anchor.snapshotId,executionKind:"terminal" as const};
 await assert.rejects(startRun(users[1],f.t.id,request),/editor_handoff_required/);
 await asUser(users[1],db=>db.query("SELECT collab.editor_checkpoint($1,'archive',1,'Release for terminal')",[session.id]));
 const accepted=await startRun(users[1],f.t.id,request),claim=(await store.claim(executor,"native"))!;assert.equal(claim.run.id,accepted.runId);
 assert.equal(await executeClaim(store,executor,claim,{dataRoot:root,backend:new NativeRuntimeBackend(),driver:async agent=>{await agent.peer.command("terminal_input",{data:"exit\r"});await agent.peer.command("terminal_wait");return{kind:"terminal"};}}),"completed");
 assert.equal(Number((await admin.query("SELECT count(*) n FROM collab_gateway.capabilities WHERE run_id=$1",[accepted.runId])).rows[0].n),0);
});
